apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-svc
spec:
  type: NodePort
  # sessionAffinity: None
  ports:
    - name: postgresql
      port: 5432
      nodePort: 30432
      # targetPort: postgresql
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
