apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  # type: NodePort
  # sessionAffinity: None
  ports:
    - name: postgresql
      port: 5432
      # nodePort: 32000
      # targetPort: postgresql
      # AsadIqbal
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres