apiVersion: v1
kind: Service
metadata:
  name: spring-kafka-producer-service
  labels:
    app: spring-kafka-producer-service
spec:
  type: NodePort
  selector:
    app: spring-kafka-producer
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kafka-producer
spec:
  selector:
    matchLabels:
      app: spring-kafka-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-kafka-producer
    spec:
      containers:
        - name: spring-kafka-producer
          # image: sumitgupta28/ocp-demo-app-kafka:latest
          image: asadiqbal6019/spring-kafka-app:1.6
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_ENDPOINT
              value: kafka:9092
